# Generated by Django 2.1.3 on 2018-11-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voivodeship_id', models.IntegerField(blank=True, null=True)),
                ('county_id', models.IntegerField(blank=True, null=True)),
                ('municipality_id', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
