# Generated by Django 2.1.3 on 2018-12-02 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fotoPXapp', '0004_auto_20181126_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_picture', models.ImageField(null=True, upload_to='')),
                ('email_privacy', models.IntegerField(choices=[(1, 'Global'), (2, 'Logged'), (3, 'OnlyMe')], default=1, null=True)),
                ('phone_number', models.CharField(max_length=14, null=True)),
                ('phone_privacy', models.IntegerField(choices=[(1, 'Global'), (2, 'Logged'), (3, 'OnlyMe')], default=1, null=True)),
                ('skype', models.CharField(max_length=64, null=True)),
                ('skype_privacy', models.IntegerField(choices=[(1, 'Global'), (2, 'Logged'), (3, 'OnlyMe')], default=1, null=True)),
                ('instagram_id', models.CharField(max_length=64, null=True)),
                ('instagram_privacy', models.IntegerField(choices=[(1, 'Global'), (2, 'Logged'), (3, 'OnlyMe')], default=1, null=True)),
                ('facebook_id', models.CharField(max_length=64, null=True)),
                ('facebook_privacy', models.IntegerField(choices=[(1, 'Global'), (2, 'Logged'), (3, 'OnlyMe')], default=1, null=True)),
                ('website', models.URLField(null=True)),
                ('website_privacy', models.IntegerField(choices=[(1, 'Global'), (2, 'Logged'), (3, 'OnlyMe')], default=1, null=True)),
                ('about_me', models.TextField()),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fotoPXapp.Regions')),
            ],
        ),
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='')),
                ('pic_thumb', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=160, null=True)),
                ('description', models.TextField()),
                ('views', models.IntegerField(default=0, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('camera_make', models.CharField(max_length=64, null=True)),
                ('lens', models.CharField(max_length=64, null=True)),
                ('focal_length', models.IntegerField(null=True)),
                ('ISO', models.IntegerField(null=True)),
                ('f_stop', models.FloatField(null=True)),
                ('shutter_speed', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PictureCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='PictureComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1024, null=True)),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PictureRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****')], null=True)),
                ('rating_date', models.DateTimeField(auto_now_add=True)),
                ('picture_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fotoPXapp.Picture')),
            ],
        ),
        migrations.CreateModel(
            name='PictureTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_date', models.DateTimeField(auto_now_add=True)),
                ('picture_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fotoPXapp.Picture')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='region',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='picturetags',
            name='picture_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fotoPXapp.Tags'),
        ),
        migrations.AddField(
            model_name='picturerating',
            name='rater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='picturecomment',
            name='commenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='picturecomment',
            name='picture_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fotoPXapp.Picture'),
        ),
        migrations.AddField(
            model_name='picture',
            name='picture_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fotoPXapp.PictureCategory'),
        ),
        migrations.AddField(
            model_name='picture',
            name='picture_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followers',
            name='follower',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
