# Generated by Django 2.1.3 on 2018-12-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoPXapp', '0005_auto_20181202_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
