# Generated by Django 2.1.3 on 2018-12-02 14:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fotoPXapp', '0007_auto_20181202_1456'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follower',
            new_name='Followers',
        ),
    ]
