# Generated by Django 2.1.3 on 2018-12-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoPXapp', '0008_auto_20181202_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturecategory',
            name='category',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='tag',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
