# Generated by Django 2.1.3 on 2018-12-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoPXapp', '0009_auto_20181202_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='pic_thumb',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
