# Generated by Django 2.1.3 on 2018-12-02 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fotoPXapp', '0010_auto_20181202_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='pic_thumb',
        ),
    ]
