# Generated by Django 2.1.3 on 2018-12-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoPXapp', '0011_remove_picture_pic_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='lens',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
