# Generated by Django 2.1.3 on 2018-12-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoPXapp', '0012_auto_20181203_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='pic_slug',
            field=models.CharField(max_length=160, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='picture',
            name='picture_thumbnail',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='picturecategory',
            name='category_slug',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
