# Generated by Django 2.1.3 on 2018-12-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoPXapp', '0013_auto_20181203_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='th_height',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='picture',
            name='th_width',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
