# Generated by Django 2.1.3 on 2018-12-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoPXapp', '0014_auto_20181204_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='th_height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='th_width',
            field=models.IntegerField(null=True),
        ),
    ]
