# Generated by Django 2.1.3 on 2018-12-04 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoPXapp', '0015_auto_20181204_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='slug',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tags',
            name='slug',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
    ]
