# Generated by Django 2.1.3 on 2018-12-06 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoPXapp', '0016_auto_20181204_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='website',
            field=models.URLField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(max_length=160, upload_to=''),
        ),
        migrations.AlterField(
            model_name='picture',
            name='picture_thumbnail',
            field=models.ImageField(max_length=160, null=True, upload_to=''),
        ),
    ]
