# Generated by Django 2.1.3 on 2018-12-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoPXapp', '0019_auto_20181211_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='shutter_speed',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
