# Generated by Django 2.1.4 on 2019-01-04 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fotoPXapp', '0020_auto_20181211_1926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extenduser',
            options={'verbose_name': 'Extended User Info', 'verbose_name_plural': 'Extended User Info'},
        ),
        migrations.AlterModelOptions(
            name='picturecategory',
            options={'verbose_name': 'Picture Categories', 'verbose_name_plural': 'Picture Categories'},
        ),
        migrations.AlterModelOptions(
            name='picturecomment',
            options={'verbose_name': 'Picture Comments', 'verbose_name_plural': 'Pictures Comments'},
        ),
        migrations.AlterModelOptions(
            name='picturerating',
            options={'verbose_name': 'Picture Ratings', 'verbose_name_plural': 'Picture Ratings'},
        ),
        migrations.AlterModelOptions(
            name='picturetags',
            options={'verbose_name': 'Picture Tags', 'verbose_name_plural': 'Picture Tags'},
        ),
        migrations.AlterModelOptions(
            name='regions',
            options={'verbose_name': 'Regions', 'verbose_name_plural': 'Regions'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'Tag List', 'verbose_name_plural': 'Tag List'},
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='avatar_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='email_privacy',
            field=models.IntegerField(blank=True, choices=[(1, 'Global'), (2, 'Logged'), (3, 'OnlyMe')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='facebook_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='facebook_privacy',
            field=models.IntegerField(blank=True, choices=[(1, 'Global'), (2, 'Logged'), (3, 'OnlyMe')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='instagram_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='instagram_privacy',
            field=models.IntegerField(blank=True, choices=[(1, 'Global'), (2, 'Logged'), (3, 'OnlyMe')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='phone_privacy',
            field=models.IntegerField(blank=True, choices=[(1, 'Global'), (2, 'Logged'), (3, 'OnlyMe')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fotoPXapp.Regions'),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='skype',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='skype_privacy',
            field=models.IntegerField(blank=True, choices=[(1, 'Global'), (2, 'Logged'), (3, 'OnlyMe')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='website',
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='website_privacy',
            field=models.IntegerField(blank=True, choices=[(1, 'Global'), (2, 'Logged'), (3, 'OnlyMe')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='ISO',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='camera_make',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='camera_model',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='creation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='f_stop',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='focal_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='lens',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='pic_slug',
            field=models.CharField(max_length=160, unique=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='picture_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fotoPXapp.PictureCategory', verbose_name='Picture Category'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='picture_thumbnail',
            field=models.ImageField(blank=True, max_length=160, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='picture',
            name='picture_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Picture Author'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='shutter_speed',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='th_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='th_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='title',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='picturecategory',
            name='category_slug',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='picturecomment',
            name='comment',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='picturecomment',
            name='commenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Pic Commenter'),
        ),
        migrations.AlterField(
            model_name='picturerating',
            name='rater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Picture Rater'),
        ),
        migrations.AlterField(
            model_name='picturerating',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****')], null=True),
        ),
        migrations.AlterField(
            model_name='picturetags',
            name='picture_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fotoPXapp.Picture', verbose_name='Pic Id'),
        ),
        migrations.AlterField(
            model_name='picturetags',
            name='picture_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fotoPXapp.Tags', verbose_name='Pic Tag Name'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='slug',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
